name: ali_pasha_graph
description: "Ali-pasha2 With GraphQl"
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dio: ^5.5.0+1
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  flutter_svg_provider: ^1.0.7
  path_provider: ^2.1.3
  flutter_screenutil: ^5.9.3

  readmore: ^3.0.0
  get_storage: ^2.1.1
  dio_cache_interceptor: ^3.5.0
  image_picker: ^1.1.2
  image_cropper: ^7.1.0
  quill_html_editor: ^2.2.8
  select2dot1: ^2.0.9
  location: ^7.0.0
  badges: ^3.1.2
  dropdown_button2: ^2.3.9



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/svg/
    - assets/images/png/
  #   - images/a_dot_ham.jpeg


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

